services:
  web:
    build: .
    image: reservationplatform-web
    ports:
      - "8080:80"
    depends_on:
      - redis
      - kafka

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  kafka:
    image: "confluentinc/cp-kafka:latest"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    volumes:
      - kafkadata:/var/lib/kafka/data

  zookeeper:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

volumes:
  redisdata:
  kafkadata:
